In [1]:
import pandas as pd
from pathlib import Path
from matplotlib import pyplot as plt

In [2]:
# GETTING ALL THE MTB FILES AND REMOVING COLUMNS WITH ALL 0s

# 1. Define la ruta de la carpeta principal
ruta_base = Path('./processed_data')

# 2. Busca todos los archivos 'mtb.tsv' en las subcarpetas
# rglob busca de forma recursiva (en todas las carpetas hijo)
archivos_tsv = ruta_base.rglob('mtb.tsv')

# 3. Leer y combinar (opcional)
lista_dataframes = []

dfs_mtb = {}

for ruta in archivos_tsv:
    print(f"Leyendo: {ruta}")
    name = ruta.parent.name
    # Leemos con sep='\t' porque es un TSV (Tab Separated Values)
    df = pd.read_csv(ruta, sep='\t')
    print(f"Dimensiones antes de limpiar: {df.shape}")
    df = df.loc[:, (df != 0).any(axis=0)] # remove columns where all values are 0
    print(f"Dimensiones después de limpiar: {df.shape}")
    dfs_mtb[name] = df

Leyendo: processed_data/FRANZOSA_IBD_2019/mtb.tsv
Dimensiones antes de limpiar: (220, 8849)
Dimensiones después de limpiar: (220, 8849)
Leyendo: processed_data/WANG_ESRD_2020/mtb.tsv
Dimensiones antes de limpiar: (287, 277)
Dimensiones después de limpiar: (287, 277)
Leyendo: processed_data/KIM_ADENOMAS_2020/mtb.tsv
Dimensiones antes de limpiar: (240, 463)
Dimensiones después de limpiar: (240, 463)
Leyendo: processed_data/MARS_IBS_2020/mtb.tsv
Dimensiones antes de limpiar: (444, 44)
Dimensiones después de limpiar: (444, 44)
Leyendo: processed_data/POYET_BIO_ML_2019/mtb.tsv
Dimensiones antes de limpiar: (164, 490)
Dimensiones después de limpiar: (164, 490)
Leyendo: processed_data/KANG_AUTISM_2017/mtb.tsv
Dimensiones antes de limpiar: (44, 62)
Dimensiones después de limpiar: (44, 60)
Leyendo: processed_data/YACHIDA_CRC_2019/mtb.tsv
Dimensiones antes de limpiar: (347, 451)
Dimensiones después de limpiar: (347, 447)
Leyendo: processed_data/JACOBS_IBD_FAMILIES_2016/mtb.tsv
Dimensiones antes de limpiar: (90, 4627)
Dimensiones después de limpiar: (90, 4627)
Leyendo: processed_data/KOSTIC_INFANTS_DIABETES_2015/mtb.tsv
Dimensiones antes de limpiar: (103, 185)
Dimensiones después de limpiar: (103, 185)
Leyendo: processed_data/WANDRO_PRETERMS_2018/mtb.tsv
Dimensiones antes de limpiar: (75, 454)
Dimensiones después de limpiar: (75, 454)
Leyendo: processed_data/ERAWIJANTARI_GASTRIC_CANCER_2020/mtb.tsv
Dimensiones antes de limpiar: (96, 525)
Dimensiones después de limpiar: (96, 419)
Leyendo: processed_data/SINHA_CRC_2016/mtb.tsv
Dimensiones antes de limpiar: (131, 531)
Dimensiones después de limpiar: (131, 531)
Leyendo: processed_data/iHMP_IBDMDB_2019/mtb.tsv
Dimensiones antes de limpiar: (382, 81868)
Dimensiones después de limpiar: (382, 81868)
Leyendo: processed_data/HE_INFANTS_MFGM_2019/mtb.tsv
Dimensiones antes de limpiar: (277, 121)
Dimensiones después de limpiar: (277, 120)

In [3]:
# GETTING ALL THE MTB FILES AND REMOVING COLUMNS WITH ALL 0s

# 1. Define la ruta de la carpeta principal
ruta_base = Path('./processed_data')

# 2. Busca todos los archivos 'genera.tsv' en las subcarpetas
# rglob busca de forma recursiva (en todas las carpetas hijo)
archivos_tsv = ruta_base.rglob('mtb.map.tsv')

# 3. Leer y combinar (opcional)
lista_dataframes = []

dfs_mtp_map = {}

for ruta in archivos_tsv:
    print(f"Leyendo: {ruta}")
    name = ruta.parent.name
    # Leemos con sep='\t' porque es un TSV (Tab Separated Values)
    df = pd.read_csv(ruta, sep='\t')
    print(f"Dimensiones antes de limpiar: {df.shape}")
    df = df.loc[:, (df != 0).any(axis=0)] # remove columns where all values are 0
    print(f"Dimensiones después de limpiar: {df.shape}")
    dfs_mtp_map[name] = df

Leyendo: processed_data/FRANZOSA_IBD_2019/mtb.map.tsv
Dimensiones antes de limpiar: (8848, 10)
Dimensiones después de limpiar: (8848, 10)
Leyendo: processed_data/WANG_ESRD_2020/mtb.map.tsv
Dimensiones antes de limpiar: (276, 4)
Dimensiones después de limpiar: (276, 4)
Leyendo: processed_data/KIM_ADENOMAS_2020/mtb.map.tsv
Dimensiones antes de limpiar: (462, 7)
Dimensiones después de limpiar: (462, 7)
Leyendo: processed_data/MARS_IBS_2020/mtb.map.tsv
Dimensiones antes de limpiar: (43, 5)
Dimensiones después de limpiar: (43, 5)
Leyendo: processed_data/POYET_BIO_ML_2019/mtb.map.tsv
Dimensiones antes de limpiar: (489, 5)
Dimensiones después de limpiar: (489, 5)
Leyendo: processed_data/KANG_AUTISM_2017/mtb.map.tsv
Dimensiones antes de limpiar: (61, 4)
Dimensiones después de limpiar: (61, 4)
Leyendo: processed_data/YACHIDA_CRC_2019/mtb.map.tsv
Dimensiones antes de limpiar: (450, 4)
Dimensiones después de limpiar: (450, 4)
Leyendo: processed_data/JACOBS_IBD_FAMILIES_2016/mtb.map.tsv
Dimensiones antes de limpiar: (4626, 13)
Dimensiones después de limpiar: (4626, 13)
Leyendo: processed_data/KOSTIC_INFANTS_DIABETES_2015/mtb.map.tsv
Dimensiones antes de limpiar: (184, 7)
Dimensiones después de limpiar: (184, 7)
Leyendo: processed_data/WANDRO_PRETERMS_2018/mtb.map.tsv
Dimensiones antes de limpiar: (453, 5)
Dimensiones después de limpiar: (453, 5)
Leyendo: processed_data/ERAWIJANTARI_GASTRIC_CANCER_2020/mtb.map.tsv
Dimensiones antes de limpiar: (524, 4)
Dimensiones después de limpiar: (524, 4)
Leyendo: processed_data/SINHA_CRC_2016/mtb.map.tsv
Dimensiones antes de limpiar: (530, 4)
Dimensiones después de limpiar: (530, 4)
Leyendo: processed_data/iHMP_IBDMDB_2019/mtb.map.tsv
Dimensiones antes de limpiar: (81867, 7)
Dimensiones después de limpiar: (81867, 7)
Leyendo: processed_data/HE_INFANTS_MFGM_2019/mtb.map.tsv
Dimensiones antes de limpiar: (120, 4)
Dimensiones después de limpiar: (120, 4)

In [4]:
# 1. Define la ruta de la carpeta principal
ruta_base = Path('./processed_data')

# 2. Busca todos los archivos 'genera.tsv' en las subcarpetas
# rglob busca de forma recursiva (en todas las carpetas hijo)
archivos_tsv = ruta_base.rglob('genera.tsv')

dfs_genera = {}

for ruta in archivos_tsv:
    print(f"Leyendo: {ruta}")
    name = ruta.parent.name  # Extrae el nombre de la carpeta padre
    # Leemos con sep='\t' porque es un TSV (Tab Separated Values)
    df = pd.read_csv(ruta, sep='\t')
    print(f"Dimensiones antes de limpiar: {df.shape}")
    df = df.loc[:, (df != 0).any(axis=0)] # remove columns where all values are 0
    print(f"Dimensiones después de limpiar: {df.shape}")
    dfs_genera[name] = df

Leyendo: processed_data/FRANZOSA_IBD_2019/genera.tsv
Dimensiones antes de limpiar: (220, 11721)
Dimensiones después de limpiar: (220, 11721)
Leyendo: processed_data/WANG_ESRD_2020/genera.tsv
Dimensiones antes de limpiar: (287, 11846)
Dimensiones después de limpiar: (287, 11839)
Leyendo: processed_data/KIM_ADENOMAS_2020/genera.tsv
Dimensiones antes de limpiar: (240, 500)
Dimensiones después de limpiar: (240, 500)
Leyendo: processed_data/MARS_IBS_2020/genera.tsv
Dimensiones antes de limpiar: (444, 2896)
Dimensiones después de limpiar: (444, 2472)
Leyendo: processed_data/POYET_BIO_ML_2019/genera.tsv
Dimensiones antes de limpiar: (164, 354)
Dimensiones después de limpiar: (164, 354)
Leyendo: processed_data/KANG_AUTISM_2017/genera.tsv
Dimensiones antes de limpiar: (44, 322)
Dimensiones después de limpiar: (44, 322)
Leyendo: processed_data/YACHIDA_CRC_2019/genera.tsv
Dimensiones antes de limpiar: (347, 11943)
Dimensiones después de limpiar: (347, 11727)
Leyendo: processed_data/JACOBS_IBD_FAMILIES_2016/genera.tsv
Dimensiones antes de limpiar: (90, 509)
Dimensiones después de limpiar: (90, 509)
Leyendo: processed_data/KOSTIC_INFANTS_DIABETES_2015/genera.tsv
Dimensiones antes de limpiar: (103, 585)
Dimensiones después de limpiar: (103, 332)
Leyendo: processed_data/WANDRO_PRETERMS_2018/genera.tsv
Dimensiones antes de limpiar: (75, 83)
Dimensiones después de limpiar: (75, 83)
Leyendo: processed_data/ERAWIJANTARI_GASTRIC_CANCER_2020/genera.tsv
Dimensiones antes de limpiar: (96, 10528)
Dimensiones después de limpiar: (96, 10425)
Leyendo: processed_data/SINHA_CRC_2016/genera.tsv
Dimensiones antes de limpiar: (131, 87)
Dimensiones después de limpiar: (131, 87)
Leyendo: processed_data/iHMP_IBDMDB_2019/genera.tsv
Dimensiones antes de limpiar: (382, 9695)
Dimensiones después de limpiar: (382, 9682)
Leyendo: processed_data/HE_INFANTS_MFGM_2019/genera.tsv
Dimensiones antes de limpiar: (277, 296)
Dimensiones después de limpiar: (277, 296)

In [5]:
# 1. Define la ruta de la carpeta principal
ruta_base = Path('./processed_data')

# 2. Busca todos los archivos 'genera.tsv' en las subcarpetas
# rglob busca de forma recursiva (en todas las carpetas hijo)
archivos_tsv = ruta_base.rglob('metadata.tsv')

dfs_metadata = {}

for ruta in archivos_tsv:
    print(f"Leyendo: {ruta}")
    name = ruta.parent.name  # Extrae el nombre de la carpeta padre
    # Leemos con sep='\t' porque es un TSV (Tab Separated Values)
    df = pd.read_csv(ruta, sep='\t')
    print(f"Dimensiones antes de limpiar: {df.shape}")
    df = df.loc[:, (df != 0).any(axis=0)] # remove columns where all values are 0
    print(f"Dimensiones después de limpiar: {df.shape}")
    dfs_metadata[name] = df

Leyendo: processed_data/FRANZOSA_IBD_2019/metadata.tsv
Dimensiones antes de limpiar: (220, 13)
Dimensiones después de limpiar: (220, 13)
Leyendo: processed_data/WANG_ESRD_2020/metadata.tsv
Dimensiones antes de limpiar: (287, 15)
Dimensiones después de limpiar: (287, 15)
Leyendo: processed_data/KIM_ADENOMAS_2020/metadata.tsv
Dimensiones antes de limpiar: (240, 12)
Dimensiones después de limpiar: (240, 12)
Leyendo: processed_data/MARS_IBS_2020/metadata.tsv
Dimensiones antes de limpiar: (444, 25)
Dimensiones después de limpiar: (444, 25)
Leyendo: processed_data/POYET_BIO_ML_2019/metadata.tsv
Dimensiones antes de limpiar: (164, 174)
Dimensiones después de limpiar: (164, 174)
Leyendo: processed_data/KANG_AUTISM_2017/metadata.tsv
Dimensiones antes de limpiar: (44, 38)
Dimensiones después de limpiar: (44, 38)
Leyendo: processed_data/YACHIDA_CRC_2019/metadata.tsv
Dimensiones antes de limpiar: (347, 15)
Dimensiones después de limpiar: (347, 15)
Leyendo: processed_data/JACOBS_IBD_FAMILIES_2016/metadata.tsv
Dimensiones antes de limpiar: (90, 11)
Dimensiones después de limpiar: (90, 11)
Leyendo: processed_data/KOSTIC_INFANTS_DIABETES_2015/metadata.tsv
Dimensiones antes de limpiar: (103, 71)
Dimensiones después de limpiar: (103, 71)
Leyendo: processed_data/WANDRO_PRETERMS_2018/metadata.tsv
Dimensiones antes de limpiar: (75, 40)
Dimensiones después de limpiar: (75, 40)
Leyendo: processed_data/ERAWIJANTARI_GASTRIC_CANCER_2020/metadata.tsv
Dimensiones antes de limpiar: (96, 52)
Dimensiones después de limpiar: (96, 52)
Leyendo: processed_data/SINHA_CRC_2016/metadata.tsv
Dimensiones antes de limpiar: (131, 13)
Dimensiones después de limpiar: (131, 13)
Leyendo: processed_data/iHMP_IBDMDB_2019/metadata.tsv
Dimensiones antes de limpiar: (382, 24)
Dimensiones después de limpiar: (382, 24)
Leyendo: processed_data/HE_INFANTS_MFGM_2019/metadata.tsv
Dimensiones antes de limpiar: (277, 12)
Dimensiones después de limpiar: (277, 12)

In [6]:
all_datasets = [
	'FRANZOSA_IBD_2019',
	'WANG_ESRD_2020',
	'KIM_ADENOMAS_2020',
	'MARS_IBS_2020',
	'POYET_BIO_ML_2019',
	'KANG_AUTISM_2017',
	'YACHIDA_CRC_2019',
	'JACOBS_IBD_FAMILIES_2016',
	'KOSTIC_INFANTS_DIABETES_2015',
	'WANDRO_PRETERMS_2018',
	'ERAWIJANTARI_GASTRIC_CANCER_2020',
	'SINHA_CRC_2016',
	'iHMP_IBDMDB_2019',
	'HE_INFANTS_MFGM_2019'
]

# MAP MTB.MAP WITH MTB DATA

In [7]:
# Remove NaN columns from HMDB, but keep KEGG if HMDB is NaN
dfs_mtb_renamed_clean = {}

#for dataset in interested_datasets:
for dataset in all_datasets:
	df = dfs_mtb[dataset].copy()
	map_df = dfs_mtp_map[dataset]
	
	# Create a mapping of old column names to new ones
	# If HMDB is NaN but KEGG exists, use KEGG; otherwise keep HMDB
	rename_dict = {}
	for idx, row in map_df.iterrows():
		old_name = row['Compound']
		hmdb = row['HMDB']
		kegg = row['KEGG']

		rename_dict[old_name] = hmdb
		if pd.isna(hmdb) and not pd.isna(kegg):
			# HMDB is NaN but KEGG is not, use KEGG
			rename_dict[old_name] = kegg

	# Rename columns based on the mapping
	df_renamed = df.rename(columns=rename_dict)
	
	dfs_mtb_renamed_clean[dataset] = df_renamed

# GET DATASET WITH MOST GENERA

In [9]:
df_mtb = dfs_mtb_renamed_clean['WANG_ESRD_2020']

In [10]:
df_mtb

,Sample,NaN,HMDB0006115,NaN,HMDB0034240,HMDB0000228,HMDB0013299,HMDB0034168,HMDB0000738,HMDB0001967,...,NaN,HMDB0243751,NaN,HMDB0302599,NaN,HMDB0038040,NaN,HMDB0033794,HMDB0011624,HMDB0030469
0,CON-001,0.011931,0.087967,0.051197,0.172107,0.049930,0.005340,0.113204,0.642949,0.031697,...,5.236453e-02,8.051328e-09,8.606949e-03,8.051328e-09,1.798532e-02,9.874148e-07,1.363812e-03,8.051328e-09,8.051328e-09,1.429219e-03
1,CON-002,0.069543,0.359398,0.191413,0.725868,0.167047,0.101231,0.579727,27.893334,0.063823,...,9.243080e-03,8.066107e-09,4.593440e-03,8.066107e-09,8.066107e-09,3.237582e-03,7.015772e-03,8.689936e-03,8.066107e-09,6.598504e-02
2,CON-003,0.064806,0.371002,0.192658,0.612681,0.093682,0.129043,1.222348,9.929321,0.174733,...,1.559581e-08,5.577590e-02,2.996485e-02,5.102441e-02,1.559581e-08,1.559581e-08,6.265439e-03,1.559581e-08,2.388436e-01,1.559581e-08
3,CON-004,0.024174,0.779997,0.144118,0.925795,0.016245,0.593587,0.927712,12.856515,0.061969,...,1.805360e-02,7.523501e-09,7.523501e-09,7.523501e-09,7.523501e-09,9.783985e-04,4.596547e-03,7.523501e-09,1.167647e-02,5.101213e-02
4,CON-005,0.019268,0.127031,0.092488,0.584368,0.012674,0.775437,0.324421,4.813590,0.009148,...,7.652018e-09,7.652018e-09,7.182517e-04,7.652018e-09,7.652018e-09,7.652018e-09,1.418566e-03,7.652018e-09,7.652018e-09,4.971664e-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,KD-219,0.043281,0.399107,0.188049,1.654339,3.581015,1.310288,0.285898,31.696957,0.253835,...,7.768872e-02,8.814835e-03,1.919101e-08,1.919101e-08,1.919101e-08,5.320631e-03,3.461297e-03,1.811109e-02,1.740265e-02,1.150905e-02
283,KD-220,0.014782,1.349298,0.070555,0.310908,1.588726,0.455715,0.287722,22.697519,0.015670,...,5.051199e-02,9.412195e-04,2.911273e-03,1.043946e-08,1.429298e-03,1.043946e-08,1.723631e-03,1.028234e-03,4.430921e-03,6.294021e-02
284,KD-221,0.019149,0.278288,0.080161,0.275156,0.428709,0.028301,0.094374,1.308955,0.090357,...,1.712191e-02,1.002137e-08,4.937165e-03,1.002137e-08,5.242574e-03,1.027191e-04,1.716353e-03,5.789263e-04,1.002137e-08,1.002137e-08
285,KD-222,0.390022,0.246633,2.645785,7.697368,66.889933,1.432668,0.841031,266.729097,1.397951,...,1.814184e-07,1.814184e-07,1.814184e-07,2.739466e-01,3.953997e-01,1.814184e-07,1.814184e-07,6.722564e-02,1.814184e-07,3.607443e-02
286,KD-223,0.030016,1.344722,0.249816,1.510607,0.672358,0.199508,0.081609,42.872887,0.062968,...,1.424872e-01,3.478548e-03,2.549115e-08,2.549115e-08,2.549115e-08,1.121489e-02,4.231893e-03,1.520567e-02,1.046836e-02,7.392700e-03

### Delete columns that are NaN

In [11]:
df_mtb = df_mtb.loc[:, df_mtb.columns.notnull()]

In [12]:
df_mtb

,Sample,HMDB0006115,HMDB0034240,HMDB0000228,HMDB0013299,HMDB0034168,HMDB0000738,HMDB0001967,HMDB0003424,HMDB0001875,...,HMDB0033167,HMDB0259164,HMDB0034976,HMDB0030070,HMDB0243751,HMDB0302599,HMDB0038040,HMDB0033794,HMDB0011624,HMDB0030469
0,CON-001,0.087967,0.172107,0.049930,0.005340,0.113204,0.642949,0.031697,0.006308,0.119956,...,8.051328e-09,0.024712,0.203744,2.145402e-03,8.051328e-09,8.051328e-09,9.874148e-07,8.051328e-09,8.051328e-09,1.429219e-03
1,CON-002,0.359398,0.725868,0.167047,0.101231,0.579727,27.893334,0.063823,0.036451,0.860116,...,8.066107e-09,0.617011,0.008808,8.066107e-09,8.066107e-09,8.066107e-09,3.237582e-03,8.689936e-03,8.066107e-09,6.598504e-02
2,CON-003,0.371002,0.612681,0.093682,0.129043,1.222348,9.929321,0.174733,0.035478,0.543809,...,1.173114e-02,0.525051,0.035445,2.066600e-02,5.577590e-02,5.102441e-02,1.559581e-08,1.559581e-08,2.388436e-01,1.559581e-08
3,CON-004,0.779997,0.925795,0.016245,0.593587,0.927712,12.856515,0.061969,0.479085,1.453788,...,7.523501e-09,0.855113,0.024657,7.197221e-03,7.523501e-09,7.523501e-09,9.783985e-04,7.523501e-09,1.167647e-02,5.101213e-02
4,CON-005,0.127031,0.584368,0.012674,0.775437,0.324421,4.813590,0.009148,0.319127,0.054782,...,7.652018e-09,0.242739,0.018636,3.322724e-03,7.652018e-09,7.652018e-09,7.652018e-09,7.652018e-09,7.652018e-09,4.971664e-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,KD-219,0.399107,1.654339,3.581015,1.310288,0.285898,31.696957,0.253835,0.886746,0.442882,...,1.919101e-08,0.166291,0.041990,4.383854e-02,8.814835e-03,1.919101e-08,5.320631e-03,1.811109e-02,1.740265e-02,1.150905e-02
283,KD-220,1.349298,0.310908,1.588726,0.455715,0.287722,22.697519,0.015670,0.300483,0.330790,...,1.559959e-02,0.100901,0.034178,4.411467e-04,9.412195e-04,1.043946e-08,1.043946e-08,1.028234e-03,4.430921e-03,6.294021e-02
284,KD-221,0.278288,0.275156,0.428709,0.028301,0.094374,1.308955,0.090357,0.035013,0.042637,...,2.972387e-02,0.137393,0.193577,2.110055e-02,1.002137e-08,1.002137e-08,1.027191e-04,5.789263e-04,1.002137e-08,1.002137e-08
285,KD-222,0.246633,7.697368,66.889933,1.432668,0.841031,266.729097,1.397951,2.510717,1.732711,...,1.814184e-07,0.814808,0.178927,1.814184e-07,1.814184e-07,2.739466e-01,1.814184e-07,6.722564e-02,1.814184e-07,3.607443e-02
286,KD-223,1.344722,1.510607,0.672358,0.199508,0.081609,42.872887,0.062968,0.453251,0.070709,...,2.549115e-08,0.496544,0.019052,1.264797e-02,3.478548e-03,2.549115e-08,1.121489e-02,1.520567e-02,1.046836e-02,7.392700e-03

### Safe metabolites

In [13]:
df_mtb.to_csv('metabolites.tsv', sep='\t', index=False)

In [30]:
df_mtb.shape

(287, 166)

# JOIN METADATA WITH GENERA AND CLEAN DATA

In [7]:
df_meta = dfs_metadata['WANG_ESRD_2020']
df_genera = dfs_genera['WANG_ESRD_2020']

In [8]:
df_meta

,Dataset,Sample,Subject,Study.Group,Age,Age.Units,Gender,BMI,DOI,Publication.Name,Source Name,Creatinine,Dialysis.Frequency,Urea,eGFR
0,WANG_ESRD_2020,CON-001,CON-001,Control,62,Years,Female,19.570000,10.1136/gutjnl-2019-319766,Aberrant gut microbiota alters host metabolome...,ESRD353,56.6,NaN,5.10,95.937269
1,WANG_ESRD_2020,CON-002,CON-002,Control,61,Years,Female,20.820000,10.1136/gutjnl-2019-319766,Aberrant gut microbiota alters host metabolome...,ESRD354,82.1,NaN,5.00,66.667323
2,WANG_ESRD_2020,CON-003,CON-003,Control,60,Years,Female,23.830000,10.1136/gutjnl-2019-319766,Aberrant gut microbiota alters host metabolome...,ESRD355,58.9,NaN,4.40,96.027921
3,WANG_ESRD_2020,CON-004,CON-004,Control,46,Years,Female,NaN,10.1136/gutjnl-2019-319766,Aberrant gut microbiota alters host metabolome...,ESRD356,52.4,NaN,4.40,110.107268
4,WANG_ESRD_2020,CON-005,CON-005,Control,45,Years,Female,21.190000,10.1136/gutjnl-2019-319766,Aberrant gut microbiota alters host metabolome...,ESRD357,53.0,NaN,4.30,110.468885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,WANG_ESRD_2020,KD-219,KD-219,ESRD,34,Years,Female,22.768834,10.1136/gutjnl-2019-319766,Aberrant gut microbiota alters host metabolome...,ESRD640,760.0,3.0,22.05,5.467900
283,WANG_ESRD_2020,KD-220,KD-220,ESRD,37,Years,Male,28.408163,10.1136/gutjnl-2019-319766,Aberrant gut microbiota alters host metabolome...,ESRD641,1328.0,3.0,22.29,3.617743
284,WANG_ESRD_2020,KD-221,KD-221,ESRD,35,Years,Male,22.857143,10.1136/gutjnl-2019-319766,Aberrant gut microbiota alters host metabolome...,ESRD642,1585.0,3.0,29.51,2.962445
285,WANG_ESRD_2020,KD-222,KD-222,ESRD,34,Years,Female,20.474990,10.1136/gutjnl-2019-319766,Aberrant gut microbiota alters host metabolome...,ESRD643,1184.0,3.0,28.34,3.199204
286,WANG_ESRD_2020,KD-223,KD-223,ESRD,51,Years,Male,24.691358,10.1136/gutjnl-2019-319766,Aberrant gut microbiota alters host metabolome...,ESRD644,550.0,3.0,12.53,9.518647

In [16]:
df_genera

,Sample,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Peptostreptococcales;f__Acidaminobacteraceae;g__Fusibacter_A,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Oscillospirales;f__CAG-272;g__Flemingibacterium,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__F0428,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Lachnoanaerobaculum,d__Bacteria;p__Firmicutes;c__Bacilli;o__Lactobacillales;f__Carnobacteriaceae;g__Carnobacterium_A,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__GCA-900066755,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Monoglobales;f__Monoglobaceae;g__Monoglobus,d__Bacteria;p__Firmicutes;c__Bacilli;o__Bacillales;f__Bacillaceae;g__Bacillus,d__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Enterobacterales;f__Enterobacteriaceae;g__PD-1,...,d__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Rhodobacterales;f__Rhodobacteraceae;g__Cribrihabitans,d__Bacteria;p__Patescibacteria;c__Microgenomatia;o__Curtissbacterales;f__GWA2-41-24;g__MFBO01,d__Bacteria;p__Patescibacteria;c__Paceibacteria;o__UBA6257;f__2-01-FULL-56-20;g__VMFW01,d__Bacteria;p__Actinobacteriota;c__Thermoleophilia;o__Gaiellales;f__Gaiellaceae;g__JACCYG01,d__Bacteria;p__Patescibacteria;c__ABY1;o__SG8-24;f__UBA9934;g__JAHISC01,d__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Rickettsiales;f__Rickettsiaceae;g__CAJBEU01,d__Bacteria;p__Patescibacteria;c__ABY1;o__SG8-24;f__GWF2-40-263;g__JACPHX01,d__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Rhizobiales;f__Xanthobacteraceae;g__GCF-000702305,d__Bacteria;p__Firmicutes;c__Bacilli;o__Izemoplasmatales;f__UBA5603;g__M55B122,d__Bacteria;p__Patescibacteria;c__ABY1;o__SBBC01;f__PEXW01;g__CAIPSZ01
0,CON-001,0.000004,0.000004,0.000065,0.000128,1.306828e-05,0.000061,0.000078,0.000003,0.000000e+00,...,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
1,CON-002,0.000002,0.000004,0.000005,0.000014,6.546411e-07,0.000582,0.000032,0.000002,0.000000e+00,...,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
2,CON-003,0.000001,0.000002,0.000004,0.000119,1.390039e-06,0.000022,0.000008,0.000005,2.156957e-06,...,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
3,CON-004,0.000001,0.000179,0.000006,0.000042,1.282748e-06,0.000133,0.000094,0.000003,0.000000e+00,...,0.0,0.0,0.0,0.0,3.043809e-07,2.391564e-07,2.174149e-07,7.392107e-07,0.000002,3.261224e-07
4,CON-005,0.000001,0.000011,0.000007,0.000025,8.170867e-07,0.000151,0.000010,0.000010,4.399698e-07,...,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,KD-219,0.000004,0.000172,0.000040,0.000071,1.707281e-06,0.000109,0.000083,0.000006,0.000000e+00,...,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
283,KD-220,0.000002,0.000001,0.000008,0.000025,6.103054e-07,0.000019,0.000027,0.000003,0.000000e+00,...,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
284,KD-221,0.000001,0.000007,0.000026,0.000073,4.281503e-06,0.000259,0.000060,0.000004,3.892275e-07,...,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
285,KD-222,0.000002,0.000008,0.000003,0.000022,9.452744e-07,0.000386,0.000026,0.000005,0.000000e+00,...,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
286,KD-223,0.000001,0.000002,0.000002,0.000014,2.627860e-07,0.000036,0.000005,0.000004,0.000000e+00,...,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00

In [9]:
df_meta.columns

Index(['Dataset', 'Sample', 'Subject', 'Study.Group', 'Age', 'Age.Units',
       'Gender', 'BMI', 'DOI', 'Publication.Name', 'Source Name', 'Creatinine',
       'Dialysis.Frequency', 'Urea', 'eGFR'],
      dtype='str')

In [10]:
df_meta.isna().sum()

Dataset                0
Sample                 0
Subject                0
Study.Group            0
Age                    0
Age.Units              0
Gender                 0
BMI                    7
DOI                    0
Publication.Name       0
Source Name            0
Creatinine             6
Dialysis.Frequency    67
Urea                   6
eGFR                   6
dtype: int64

In [11]:
df_meta_clean = df_meta.fillna(0, inplace=True)

In [12]:
df_meta_clean.isna().sum()

Dataset               0
Sample                0
Subject               0
Study.Group           0
Age                   0
Age.Units             0
Gender                0
BMI                   0
DOI                   0
Publication.Name      0
Source Name           0
Creatinine            0
Dialysis.Frequency    0
Urea                  0
eGFR                  0
dtype: int64

In [21]:

from sklearn.preprocessing import StandardScaler

# 1. Load your dataset
df = df_meta_clean

# 2. Set 'Sample' as index (important for merging with abundance data later)
df.set_index('Sample', inplace=True)

# 3. Drop administrative columns
cols_to_drop = ['Dataset', 'Subject', 'Age.Units', 'DOI', 'Publication.Name', 'Source Name']
df_clean = df.drop(columns=cols_to_drop)

# 4. One-Hot Encoding (Creates the "ENV1, ENV2" binary style)
# This will turn 'Gender' into 'Gender_Male' and 'Study.Group' into 'Study.Group_Control'
df_encoded = pd.get_dummies(df_clean, columns=['Study.Group', 'Gender'], drop_first=True)

# 5. Handle Missing Values (NAs)
# Machine learning models can't handle NAs. Impute with median for biological markers.
bio_markers = ['Age', 'BMI', 'Creatinine', 'Urea', 'eGFR', 'Dialysis.Frequency']
#df_encoded[bio_markers] = df_encoded[bio_markers].fillna(df_encoded[bio_markers].median())

# 6. Standardize (The "ENV6" floating-point style)
scaler = StandardScaler()
df_encoded[bio_markers] = scaler.fit_transform(df_encoded[bio_markers])

# This is now your "oneHotTest" formatted table
print(df_encoded.head())

              Age       BMI  Creatinine  Dialysis.Frequency      Urea  \
Sample
CON-001  0.873449 -0.662060   -1.432282           -1.743702 -1.344308
CON-002  0.786739 -0.428630   -1.374826           -1.743702 -1.353936
CON-003  0.700028  0.133469   -1.427100           -1.743702 -1.411707
CON-004 -0.513918 -4.316635   -1.441745           -1.743702 -1.411707
CON-005 -0.600629 -0.359535   -1.440393           -1.743702 -1.421336

             eGFR  Study.Group_ESRD  Gender_Male
Sample
CON-001  1.604448             False        False
CON-002  0.910216             False        False
CON-003  1.606598             False        False
CON-004  1.940536             False        False
CON-005  1.949113             False        False

### Merge genera with metadata clean

In [22]:
# Assuming df1 and df2 both have a 'Sample' column
merged_df = pd.merge(df_genera, df_encoded, on='Sample')

In [23]:
merged_df

,Sample,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Peptostreptococcales;f__Acidaminobacteraceae;g__Fusibacter_A,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Oscillospirales;f__CAG-272;g__Flemingibacterium,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__F0428,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Lachnoanaerobaculum,d__Bacteria;p__Firmicutes;c__Bacilli;o__Lactobacillales;f__Carnobacteriaceae;g__Carnobacterium_A,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__GCA-900066755,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Monoglobales;f__Monoglobaceae;g__Monoglobus,d__Bacteria;p__Firmicutes;c__Bacilli;o__Bacillales;f__Bacillaceae;g__Bacillus,d__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Enterobacterales;f__Enterobacteriaceae;g__PD-1,...,d__Bacteria;p__Firmicutes;c__Bacilli;o__Izemoplasmatales;f__UBA5603;g__M55B122,d__Bacteria;p__Patescibacteria;c__ABY1;o__SBBC01;f__PEXW01;g__CAIPSZ01,Age,BMI,Creatinine,Dialysis.Frequency,Urea,eGFR,Study.Group_ESRD,Gender_Male
0,CON-001,0.000004,0.000004,0.000065,0.000128,1.306828e-05,0.000061,0.000078,0.000003,0.000000e+00,...,0.000000,0.000000e+00,0.873449,-0.662060,-1.432282,-1.743702,-1.344308,1.604448,False,False
1,CON-002,0.000002,0.000004,0.000005,0.000014,6.546411e-07,0.000582,0.000032,0.000002,0.000000e+00,...,0.000000,0.000000e+00,0.786739,-0.428630,-1.374826,-1.743702,-1.353936,0.910216,False,False
2,CON-003,0.000001,0.000002,0.000004,0.000119,1.390039e-06,0.000022,0.000008,0.000005,2.156957e-06,...,0.000000,0.000000e+00,0.700028,0.133469,-1.427100,-1.743702,-1.411707,1.606598,False,False
3,CON-004,0.000001,0.000179,0.000006,0.000042,1.282748e-06,0.000133,0.000094,0.000003,0.000000e+00,...,0.000002,3.261224e-07,-0.513918,-4.316635,-1.441745,-1.743702,-1.411707,1.940536,False,False
4,CON-005,0.000001,0.000011,0.000007,0.000025,8.170867e-07,0.000151,0.000010,0.000010,4.399698e-07,...,0.000000,0.000000e+00,-0.600629,-0.359535,-1.440393,-1.743702,-1.421336,1.949113,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,KD-219,0.000004,0.000172,0.000040,0.000071,1.707281e-06,0.000109,0.000083,0.000006,0.000000e+00,...,0.000000,0.000000e+00,-1.554444,-0.064697,0.152592,0.654585,0.287725,-0.541328,True,False
283,KD-220,0.000002,0.000001,0.000008,0.000025,6.103054e-07,0.000019,0.000027,0.000003,0.000000e+00,...,0.000000,0.000000e+00,-1.294312,0.988412,1.432387,0.654585,0.310833,-0.585211,True,True
284,KD-221,0.000001,0.000007,0.000026,0.000073,4.281503e-06,0.000259,0.000060,0.000004,3.892275e-07,...,0.000000,0.000000e+00,-1.467733,-0.048206,2.011449,0.654585,1.006012,-0.600753,True,True
285,KD-222,0.000002,0.000008,0.000003,0.000022,9.452744e-07,0.000386,0.000026,0.000005,0.000000e+00,...,0.000000,0.000000e+00,-1.554444,-0.493059,1.107932,0.654585,0.893358,-0.595138,True,False
286,KD-223,0.000001,0.000002,0.000002,0.000014,2.627860e-07,0.000036,0.000005,0.000004,0.000000e+00,...,0.000000,0.000000e+00,-0.080366,0.294322,-0.320572,0.654585,-0.628909,-0.445251,True,True

In [24]:
merged_df.set_index('Sample', inplace=True)

In [27]:
merged_df

,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Peptostreptococcales;f__Acidaminobacteraceae;g__Fusibacter_A,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Oscillospirales;f__CAG-272;g__Flemingibacterium,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__F0428,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Lachnoanaerobaculum,d__Bacteria;p__Firmicutes;c__Bacilli;o__Lactobacillales;f__Carnobacteriaceae;g__Carnobacterium_A,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__GCA-900066755,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Monoglobales;f__Monoglobaceae;g__Monoglobus,d__Bacteria;p__Firmicutes;c__Bacilli;o__Bacillales;f__Bacillaceae;g__Bacillus,d__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Enterobacterales;f__Enterobacteriaceae;g__PD-1,d__Bacteria;p__Firmicutes_B;c__Syntrophomonadia;o__Syntrophomonadales;f__Syntrophomonadaceae;g__JAAYJK01,...,d__Bacteria;p__Firmicutes;c__Bacilli;o__Izemoplasmatales;f__UBA5603;g__M55B122,d__Bacteria;p__Patescibacteria;c__ABY1;o__SBBC01;f__PEXW01;g__CAIPSZ01,Age,BMI,Creatinine,Dialysis.Frequency,Urea,eGFR,Study.Group_ESRD,Gender_Male
Sample,,,,,,,,,,,,,,,,,,,,,
CON-001,0.000004,0.000004,0.000065,0.000128,1.306828e-05,0.000061,0.000078,0.000003,0.000000e+00,7.875973e-07,...,0.000000,0.000000e+00,0.873449,-0.662060,-1.432282,-1.743702,-1.344308,1.604448,False,False
CON-002,0.000002,0.000004,0.000005,0.000014,6.546411e-07,0.000582,0.000032,0.000002,0.000000e+00,5.455343e-07,...,0.000000,0.000000e+00,0.786739,-0.428630,-1.374826,-1.743702,-1.353936,0.910216,False,False
CON-003,0.000001,0.000002,0.000004,0.000119,1.390039e-06,0.000022,0.000008,0.000005,2.156957e-06,2.636281e-07,...,0.000000,0.000000e+00,0.700028,0.133469,-1.427100,-1.743702,-1.411707,1.606598,False,False
CON-004,0.000001,0.000179,0.000006,0.000042,1.282748e-06,0.000133,0.000094,0.000003,0.000000e+00,9.131426e-07,...,0.000002,3.261224e-07,-0.513918,-4.316635,-1.441745,-1.743702,-1.411707,1.940536,False,False
CON-005,0.000001,0.000011,0.000007,0.000025,8.170867e-07,0.000151,0.000010,0.000010,4.399698e-07,3.980679e-07,...,0.000000,0.000000e+00,-0.600629,-0.359535,-1.440393,-1.743702,-1.421336,1.949113,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
KD-219,0.000004,0.000172,0.000040,0.000071,1.707281e-06,0.000109,0.000083,0.000006,0.000000e+00,1.401499e-06,...,0.000000,0.000000e+00,-1.554444,-0.064697,0.152592,0.654585,0.287725,-0.541328,True,False
KD-220,0.000002,0.000001,0.000008,0.000025,6.103054e-07,0.000019,0.000027,0.000003,0.000000e+00,6.611642e-07,...,0.000000,0.000000e+00,-1.294312,0.988412,1.432387,0.654585,0.310833,-0.585211,True,True
KD-221,0.000001,0.000007,0.000026,0.000073,4.281503e-06,0.000259,0.000060,0.000004,3.892275e-07,2.770384e-06,...,0.000000,0.000000e+00,-1.467733,-0.048206,2.011449,0.654585,1.006012,-0.600753,True,True
KD-222,0.000002,0.000008,0.000003,0.000022,9.452744e-07,0.000386,0.000026,0.000005,0.000000e+00,8.271151e-07,...,0.000000,0.000000e+00,-1.554444,-0.493059,1.107932,0.654585,0.893358,-0.595138,True,False
KD-223,0.000001,0.000002,0.000002,0.000014,2.627860e-07,0.000036,0.000005,0.000004,0.000000e+00,0.000000e+00,...,0.000000,0.000000e+00,-0.080366,0.294322,-0.320572,0.654585,-0.628909,-0.445251,True,True

In [28]:
merged_df.to_csv('meta_with_genera.tsv', sep='\t', index=False)

In [29]:
merged_df.shape

(287, 11846)

In [19]:
df_genera

,Sample,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Peptostreptococcales;f__Acidaminobacteraceae;g__Fusibacter_A,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Oscillospirales;f__CAG-272;g__Flemingibacterium,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__F0428,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Lachnoanaerobaculum,d__Bacteria;p__Firmicutes;c__Bacilli;o__Lactobacillales;f__Carnobacteriaceae;g__Carnobacterium_A,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__GCA-900066755,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Monoglobales;f__Monoglobaceae;g__Monoglobus,d__Bacteria;p__Firmicutes;c__Bacilli;o__Bacillales;f__Bacillaceae;g__Bacillus,d__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Enterobacterales;f__Enterobacteriaceae;g__PD-1,...,d__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Rhodobacterales;f__Rhodobacteraceae;g__Cribrihabitans,d__Bacteria;p__Patescibacteria;c__Microgenomatia;o__Curtissbacterales;f__GWA2-41-24;g__MFBO01,d__Bacteria;p__Patescibacteria;c__Paceibacteria;o__UBA6257;f__2-01-FULL-56-20;g__VMFW01,d__Bacteria;p__Actinobacteriota;c__Thermoleophilia;o__Gaiellales;f__Gaiellaceae;g__JACCYG01,d__Bacteria;p__Patescibacteria;c__ABY1;o__SG8-24;f__UBA9934;g__JAHISC01,d__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Rickettsiales;f__Rickettsiaceae;g__CAJBEU01,d__Bacteria;p__Patescibacteria;c__ABY1;o__SG8-24;f__GWF2-40-263;g__JACPHX01,d__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Rhizobiales;f__Xanthobacteraceae;g__GCF-000702305,d__Bacteria;p__Firmicutes;c__Bacilli;o__Izemoplasmatales;f__UBA5603;g__M55B122,d__Bacteria;p__Patescibacteria;c__ABY1;o__SBBC01;f__PEXW01;g__CAIPSZ01
0,CON-001,0.000004,0.000004,0.000065,0.000128,1.306828e-05,0.000061,0.000078,0.000003,0.000000e+00,...,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
1,CON-002,0.000002,0.000004,0.000005,0.000014,6.546411e-07,0.000582,0.000032,0.000002,0.000000e+00,...,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
2,CON-003,0.000001,0.000002,0.000004,0.000119,1.390039e-06,0.000022,0.000008,0.000005,2.156957e-06,...,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
3,CON-004,0.000001,0.000179,0.000006,0.000042,1.282748e-06,0.000133,0.000094,0.000003,0.000000e+00,...,0.0,0.0,0.0,0.0,3.043809e-07,2.391564e-07,2.174149e-07,7.392107e-07,0.000002,3.261224e-07
4,CON-005,0.000001,0.000011,0.000007,0.000025,8.170867e-07,0.000151,0.000010,0.000010,4.399698e-07,...,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,KD-219,0.000004,0.000172,0.000040,0.000071,1.707281e-06,0.000109,0.000083,0.000006,0.000000e+00,...,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
283,KD-220,0.000002,0.000001,0.000008,0.000025,6.103054e-07,0.000019,0.000027,0.000003,0.000000e+00,...,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
284,KD-221,0.000001,0.000007,0.000026,0.000073,4.281503e-06,0.000259,0.000060,0.000004,3.892275e-07,...,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
285,KD-222,0.000002,0.000008,0.000003,0.000022,9.452744e-07,0.000386,0.000026,0.000005,0.000000e+00,...,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
286,KD-223,0.000001,0.000002,0.000002,0.000014,2.627860e-07,0.000036,0.000005,0.000004,0.000000e+00,...,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00

In [20]:
df_meta_clean_filtered = df_meta_clean[['Sample', 'Study.Group']]

In [24]:
df_meta_clean_filtered

        Study.Group
Sample
CON-001     Control
CON-002     Control
CON-003     Control
CON-004     Control
CON-005     Control
...             ...
KD-219         ESRD
KD-220         ESRD
KD-221         ESRD
KD-222         ESRD
KD-223         ESRD

[287 rows x 1 columns]

In [22]:
df_meta_clean_filtered.set_index('Sample', inplace=True)

In [23]:
df_meta_clean_filtered['Study.Group'].value_counts()

Study.Group
ESRD       220
Control     67
Name: count, dtype: int64

In [25]:
df_meta_clean_filtered['Study.Group'] = df_meta_clean_filtered['Study.Group'].map({'ESRD': 1, 'Control': 0})

In [26]:
df_meta_clean_filtered

         Study.Group
Sample
CON-001            0
CON-002            0
CON-003            0
CON-004            0
CON-005            0
...              ...
KD-219             1
KD-220             1
KD-221             1
KD-222             1
KD-223             1

[287 rows x 1 columns]

In [53]:
# Assuming df1 and df2 both have a 'Sample' column
df_healthy_and_unhealthy = pd.merge(df_genera, df_meta_clean_filtered, on='Sample')

In [54]:
df_healthy_and_unhealthy

,Sample,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Peptostreptococcales;f__Acidaminobacteraceae;g__Fusibacter_A,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Oscillospirales;f__CAG-272;g__Flemingibacterium,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__F0428,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Lachnoanaerobaculum,d__Bacteria;p__Firmicutes;c__Bacilli;o__Lactobacillales;f__Carnobacteriaceae;g__Carnobacterium_A,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__GCA-900066755,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Monoglobales;f__Monoglobaceae;g__Monoglobus,d__Bacteria;p__Firmicutes;c__Bacilli;o__Bacillales;f__Bacillaceae;g__Bacillus,d__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Enterobacterales;f__Enterobacteriaceae;g__PD-1,...,d__Bacteria;p__Patescibacteria;c__Microgenomatia;o__Curtissbacterales;f__GWA2-41-24;g__MFBO01,d__Bacteria;p__Patescibacteria;c__Paceibacteria;o__UBA6257;f__2-01-FULL-56-20;g__VMFW01,d__Bacteria;p__Actinobacteriota;c__Thermoleophilia;o__Gaiellales;f__Gaiellaceae;g__JACCYG01,d__Bacteria;p__Patescibacteria;c__ABY1;o__SG8-24;f__UBA9934;g__JAHISC01,d__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Rickettsiales;f__Rickettsiaceae;g__CAJBEU01,d__Bacteria;p__Patescibacteria;c__ABY1;o__SG8-24;f__GWF2-40-263;g__JACPHX01,d__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Rhizobiales;f__Xanthobacteraceae;g__GCF-000702305,d__Bacteria;p__Firmicutes;c__Bacilli;o__Izemoplasmatales;f__UBA5603;g__M55B122,d__Bacteria;p__Patescibacteria;c__ABY1;o__SBBC01;f__PEXW01;g__CAIPSZ01,Study.Group
0,CON-001,0.000004,0.000004,0.000065,0.000128,1.306828e-05,0.000061,0.000078,0.000003,0.000000e+00,...,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0
1,CON-002,0.000002,0.000004,0.000005,0.000014,6.546411e-07,0.000582,0.000032,0.000002,0.000000e+00,...,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0
2,CON-003,0.000001,0.000002,0.000004,0.000119,1.390039e-06,0.000022,0.000008,0.000005,2.156957e-06,...,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0
3,CON-004,0.000001,0.000179,0.000006,0.000042,1.282748e-06,0.000133,0.000094,0.000003,0.000000e+00,...,0.0,0.0,0.0,3.043809e-07,2.391564e-07,2.174149e-07,7.392107e-07,0.000002,3.261224e-07,0
4,CON-005,0.000001,0.000011,0.000007,0.000025,8.170867e-07,0.000151,0.000010,0.000010,4.399698e-07,...,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,KD-219,0.000004,0.000172,0.000040,0.000071,1.707281e-06,0.000109,0.000083,0.000006,0.000000e+00,...,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,1
283,KD-220,0.000002,0.000001,0.000008,0.000025,6.103054e-07,0.000019,0.000027,0.000003,0.000000e+00,...,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,1
284,KD-221,0.000001,0.000007,0.000026,0.000073,4.281503e-06,0.000259,0.000060,0.000004,3.892275e-07,...,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,1
285,KD-222,0.000002,0.000008,0.000003,0.000022,9.452744e-07,0.000386,0.000026,0.000005,0.000000e+00,...,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,1
286,KD-223,0.000001,0.000002,0.000002,0.000014,2.627860e-07,0.000036,0.000005,0.000004,0.000000e+00,...,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,1

In [55]:
# we run this if we want only the 10% more abundant genera
genera_cols = [c for c in df_healthy_and_unhealthy.columns if c != 'Sample']
col_means = df_healthy_and_unhealthy[genera_cols].mean()
threshold = col_means.quantile(0.8)

top_genera = col_means[col_means >= threshold].index.tolist()

df_healthy_and_unhealthy = df_healthy_and_unhealthy[['Sample'] + top_genera]
df_healthy_and_unhealthy.head()

,Sample,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Peptostreptococcales;f__Acidaminobacteraceae;g__Fusibacter_A,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Oscillospirales;f__CAG-272;g__Flemingibacterium,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__F0428,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Lachnoanaerobaculum,d__Bacteria;p__Firmicutes;c__Bacilli;o__Lactobacillales;f__Carnobacteriaceae;g__Carnobacterium_A,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__GCA-900066755,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Monoglobales;f__Monoglobaceae;g__Monoglobus,d__Bacteria;p__Firmicutes;c__Bacilli;o__Bacillales;f__Bacillaceae;g__Bacillus,d__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Enterobacterales;f__Enterobacteriaceae;g__PD-1,...,d__Bacteria;p__Desulfobacterota_I;c__Desulfovibrionia;o__Desulfovibrionales;f__Desulfovibrionaceae;g__Nitratidesulfovibrio,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Christensenellales;f__Borkfalkiaceae;g__SIG402,d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__VadinHA17;g__DUOU01,d__Bacteria;p__CLD3;c__CLD3;o__SB21;f__SB21;g__JABWCP01,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Christensenellales;f__HGM11417;g__JAAYQN01,d__Bacteria;p__Verrucomicrobiota;c__Lentisphaeria;o__Victivallales;f__Victivallaceae;g__UMGS1518,d__Bacteria;p__Firmicutes;c__Bacilli;o__Staphylococcales;f__DSM-29158;g__Abyssicoccus,d__Bacteria;p__Firmicutes;c__Bacilli;o__RFN20;f__CAG-288;g__CAJMBK01,d__Bacteria;p__Firmicutes;c__Bacilli;o__Lactobacillales;f__Catellicoccaceae;g__Catellicoccus,Study.Group
0,CON-001,0.000004,0.000004,0.000065,0.000128,1.306828e-05,0.000061,0.000078,0.000003,0.000000e+00,...,0.000000e+00,5.834054e-07,0.000000e+00,0.000000e+00,0.0,0.000000,0.0,0.0,0.0,0
1,CON-002,0.000002,0.000004,0.000005,0.000014,6.546411e-07,0.000582,0.000032,0.000002,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000,0.0,0.0,0.0,0
2,CON-003,0.000001,0.000002,0.000004,0.000119,1.390039e-06,0.000022,0.000008,0.000005,2.156957e-06,...,4.793239e-07,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000,0.0,0.0,0.0,0
3,CON-004,0.000001,0.000179,0.000006,0.000042,1.282748e-06,0.000133,0.000094,0.000003,0.000000e+00,...,0.000000e+00,2.108925e-06,3.261224e-07,5.217958e-07,0.0,0.000002,0.0,0.0,0.0,0
4,CON-005,0.000001,0.000011,0.000007,0.000025,8.170867e-07,0.000151,0.000010,0.000010,4.399698e-07,...,2.304603e-07,0.000000e+00,0.000000e+00,4.399698e-07,0.0,0.000000,0.0,0.0,0.0,0

In [56]:
df_healthy_and_unhealthy.shape

(287, 2369)

In [57]:
df_healthy = df_healthy_and_unhealthy[df_healthy_and_unhealthy['Study.Group'] == 0]
df_unhealthy = df_healthy_and_unhealthy[df_healthy_and_unhealthy['Study.Group'] == 1]

In [58]:
df_healthy = df_healthy.drop(columns=['Study.Group'])
df_unhealthy = df_unhealthy.drop(columns=['Study.Group'])

In [59]:
df_healthy

,Sample,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Peptostreptococcales;f__Acidaminobacteraceae;g__Fusibacter_A,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Oscillospirales;f__CAG-272;g__Flemingibacterium,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__F0428,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Lachnoanaerobaculum,d__Bacteria;p__Firmicutes;c__Bacilli;o__Lactobacillales;f__Carnobacteriaceae;g__Carnobacterium_A,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__GCA-900066755,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Monoglobales;f__Monoglobaceae;g__Monoglobus,d__Bacteria;p__Firmicutes;c__Bacilli;o__Bacillales;f__Bacillaceae;g__Bacillus,d__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Enterobacterales;f__Enterobacteriaceae;g__PD-1,...,d__Bacteria;p__Verrucomicrobiota;c__Verrucomicrobiae;o__Opitutales;f__CAG-312;g__QALA01,d__Bacteria;p__Desulfobacterota_I;c__Desulfovibrionia;o__Desulfovibrionales;f__Desulfovibrionaceae;g__Nitratidesulfovibrio,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Christensenellales;f__Borkfalkiaceae;g__SIG402,d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__VadinHA17;g__DUOU01,d__Bacteria;p__CLD3;c__CLD3;o__SB21;f__SB21;g__JABWCP01,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Christensenellales;f__HGM11417;g__JAAYQN01,d__Bacteria;p__Verrucomicrobiota;c__Lentisphaeria;o__Victivallales;f__Victivallaceae;g__UMGS1518,d__Bacteria;p__Firmicutes;c__Bacilli;o__Staphylococcales;f__DSM-29158;g__Abyssicoccus,d__Bacteria;p__Firmicutes;c__Bacilli;o__RFN20;f__CAG-288;g__CAJMBK01,d__Bacteria;p__Firmicutes;c__Bacilli;o__Lactobacillales;f__Catellicoccaceae;g__Catellicoccus
0,CON-001,4.215104e-06,0.000004,0.000065,0.000128,1.306828e-05,0.000061,0.000078,0.000003,0.000000e+00,...,0.000000e+00,0.000000e+00,5.834054e-07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.0
1,CON-002,2.094852e-06,0.000004,0.000005,0.000014,6.546411e-07,0.000582,0.000032,0.000002,0.000000e+00,...,3.054992e-07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.0
2,CON-003,1.006580e-06,0.000002,0.000004,0.000119,1.390039e-06,0.000022,0.000008,0.000005,2.156957e-06,...,0.000000e+00,4.793239e-07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.0
3,CON-004,1.152299e-06,0.000179,0.000006,0.000042,1.282748e-06,0.000133,0.000094,0.000003,0.000000e+00,...,7.196433e-06,0.000000e+00,2.108925e-06,3.261224e-07,5.217958e-07,0.000000e+00,2.217632e-06,0.0,0.000000e+00,0.0
4,CON-005,1.382762e-06,0.000011,0.000007,0.000025,8.170867e-07,0.000151,0.000010,0.000010,4.399698e-07,...,0.000000e+00,2.304603e-07,0.000000e+00,0.000000e+00,4.399698e-07,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,CON-065,1.358743e-06,0.000457,0.000009,0.000061,1.811657e-06,0.000047,0.000017,0.000004,0.000000e+00,...,3.623315e-06,0.000000e+00,8.626940e-07,0.000000e+00,0.000000e+00,4.313470e-07,2.588082e-07,0.0,6.685879e-07,0.0
63,CON-066,3.611241e-06,0.000140,0.000009,0.000035,1.795533e-06,0.000027,0.000013,0.000006,0.000000e+00,...,3.026180e-06,0.000000e+00,8.675049e-07,0.000000e+00,0.000000e+00,0.000000e+00,4.640142e-07,0.0,0.000000e+00,0.0
64,CON-067,9.474472e-07,0.000155,0.000003,0.000037,1.512271e-06,0.000050,0.000014,0.000007,0.000000e+00,...,2.405058e-06,0.000000e+00,2.915222e-07,8.927868e-07,0.000000e+00,0.000000e+00,2.222857e-06,0.0,0.000000e+00,0.0
65,CON-068,1.381300e-06,0.000003,0.000022,0.000037,1.454000e-06,0.000017,0.000017,0.000006,1.623633e-06,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.665666e-07,0.000000e+00,0.000000e+00,0.0,2.423333e-07,0.0
66,CON-069,1.039409e-06,0.000001,0.000109,0.000041,8.909217e-07,0.000010,0.000003,0.000004,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.0

In [60]:
df_unhealthy

,Sample,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Peptostreptococcales;f__Acidaminobacteraceae;g__Fusibacter_A,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Oscillospirales;f__CAG-272;g__Flemingibacterium,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__F0428,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Lachnoanaerobaculum,d__Bacteria;p__Firmicutes;c__Bacilli;o__Lactobacillales;f__Carnobacteriaceae;g__Carnobacterium_A,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__GCA-900066755,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Monoglobales;f__Monoglobaceae;g__Monoglobus,d__Bacteria;p__Firmicutes;c__Bacilli;o__Bacillales;f__Bacillaceae;g__Bacillus,d__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Enterobacterales;f__Enterobacteriaceae;g__PD-1,...,d__Bacteria;p__Verrucomicrobiota;c__Verrucomicrobiae;o__Opitutales;f__CAG-312;g__QALA01,d__Bacteria;p__Desulfobacterota_I;c__Desulfovibrionia;o__Desulfovibrionales;f__Desulfovibrionaceae;g__Nitratidesulfovibrio,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Christensenellales;f__Borkfalkiaceae;g__SIG402,d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__VadinHA17;g__DUOU01,d__Bacteria;p__CLD3;c__CLD3;o__SB21;f__SB21;g__JABWCP01,d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Christensenellales;f__HGM11417;g__JAAYQN01,d__Bacteria;p__Verrucomicrobiota;c__Lentisphaeria;o__Victivallales;f__Victivallaceae;g__UMGS1518,d__Bacteria;p__Firmicutes;c__Bacilli;o__Staphylococcales;f__DSM-29158;g__Abyssicoccus,d__Bacteria;p__Firmicutes;c__Bacilli;o__RFN20;f__CAG-288;g__CAJMBK01,d__Bacteria;p__Firmicutes;c__Bacilli;o__Lactobacillales;f__Catellicoccaceae;g__Catellicoccus
67,KD-001,2.420281e-06,0.000006,0.000012,0.000043,6.205849e-07,0.000043,0.000653,0.000004,0.000000e+00,...,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000001,0.0,0.0,0.0
68,KD-002,7.495525e-07,0.000006,0.000004,0.000024,3.281825e-06,0.000030,0.000006,0.000003,1.478847e-06,...,0.000000,2.714596e-06,0.000000e+00,3.038727e-07,2.836145e-07,0.000000e+00,0.000000,0.0,0.0,0.0
69,KD-003,1.113030e-06,0.000114,0.000018,0.000035,1.141569e-06,0.000082,0.000037,0.000005,0.000000e+00,...,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.0,0.0,0.0
70,KD-004,2.687042e-06,0.000010,0.000006,0.000021,1.974153e-06,0.000855,0.000014,0.000007,0.000000e+00,...,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.0,0.0,0.0
71,KD-005,2.984842e-06,0.000029,0.000006,0.000027,1.492421e-06,0.000211,0.000179,0.000006,0.000000e+00,...,0.000000,3.859710e-07,0.000000e+00,0.000000e+00,3.345082e-07,0.000000e+00,0.000001,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,KD-219,4.255462e-06,0.000172,0.000040,0.000071,1.707281e-06,0.000109,0.000083,0.000006,0.000000e+00,...,0.000002,4.077089e-07,0.000000e+00,8.918633e-07,0.000000e+00,3.057817e-07,0.000002,0.0,0.0,0.0
283,KD-220,1.856346e-06,0.000001,0.000008,0.000025,6.103054e-07,0.000019,0.000027,0.000003,0.000000e+00,...,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.0,0.0,0.0
284,KD-221,1.213474e-06,0.000007,0.000026,0.000073,4.281503e-06,0.000259,0.000060,0.000004,3.892275e-07,...,0.000000,0.000000e+00,0.000000e+00,2.289574e-07,6.639763e-07,0.000000e+00,0.000000,0.0,0.0,0.0
285,KD-222,2.268658e-06,0.000008,0.000003,0.000022,9.452744e-07,0.000386,0.000026,0.000005,0.000000e+00,...,0.000000,0.000000e+00,5.671646e-07,9.535455e-05,5.293536e-06,0.000000e+00,0.000000,0.0,0.0,0.0
286,KD-223,1.098923e-06,0.000002,0.000002,0.000014,2.627860e-07,0.000036,0.000005,0.000004,0.000000e+00,...,0.000000,3.344549e-07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.0,0.0,0.0

In [61]:
df_healthy.to_csv('df_healthy_abundant_genera_20.tsv', sep='\t', index=False)
df_unhealthy.to_csv('df_unhealthy_abundant_genera_20.tsv', sep='\t', index=False)

In [47]:
df_healthy.shape, df_unhealthy.shape

((67, 1184), (220, 1184))